apiVersion : apps/v1
kind: Deployment
metadata:
  name: okrusermanagement 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okrusermanagement
  template:
    metadata:
      labels:
        app: okrusermanagement 
    spec:
      containers:
        - name: okrusermanagement 
          image: unlockokrregistryuat.azurecr.io/okrusermanagement
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "UAT"
          - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
            value: "true"